### PR TITLE
Work

### PR DESCRIPTION
**Pull request by Ealb**
* Fir bolg stuff
* Basic dantih/tusked one stuff
* Pretty much just making sure I have remote access to what I'm currently working on so we don't have a repeat of Tuesday where I just go off and do something totally random in my free time

### CODE REVIEW

**Comment by elmokki** [comment]
To be fair, those elephant men are the most glorious Dominions thing I have seen in a good while8.12.2016 19.59 Ealb <notifications@github.com> kirjoitti:Fir bolg stuffBasic dantih/tusked one stuffPretty much just making sure I have remote access to what I'm currently working on so we don't have a repeat of Tuesday where I just go off and do something totally random in my free time



You can view, comment on, or merge this pull request online at:
  https://github.com/elmokki/nationgen/pull/751

Commit Summary
Work

File Changes

    M
    data/items/firbolg/bonusranged.txt
    (12)
  
    A
    data/items/firbolg/lance.txt
    (23)
  
    A
    data/items/firbolg/mounts.txt
    (241)
  
    A
    data/items/firbolg/overlay.txt
    (15)
  
    A
    data/items/firbolg/quiver.txt
    (5)
  
    M
    data/items/firbolg/ranged.txt
    (21)
  
    M
    data/poses/firbolg/mages.txt
    (6)
  
    A
    graphics/enlightened/dantih/basesprite_dantih.png
    (0)
  
    A
    graphics/enlightened/dantih/hands.png
    (0)
  
    A
    graphics/enlightened/dantih/hands2.png
    (0)
  
    A
    graphics/enlightened/dantih/pants__recolormask.png
    (0)
  
    A
    graphics/enlightened/dantih/pants_dark.png
    (0)
  
    A
    graphics/enlightened/dantih/pants_light.png
    (0)
  
    A
    graphics/enlightened/dantih/pants_medium.png
    (0)
  
    A
    graphics/enlightened/dantih/shadow.png
    (0)
  
    A
    graphics/firbolg/weapon/blowpipe.png
    (0)
  
    A
    graphics/firbolg/weapon/bow.png
    (0)
  
    A
    graphics/firbolg/weapon/quiver.png
    (0)
  

Patch Links:
https://github.com/elmokki/nationgen/pull/751.patchhttps://github.com/elmokki/nationgen/pull/751.diff

**Comment by Ealb** [comment]
They did turn out *a lot* better than I expected given how old and blurry the not-updated-to-Dom4-standards Celestial Servant sprite is. I'm a bit dicey about how to give them stats; they're quite short for size-5 but rather fat for size-4. I think I may give them roughly-Celestial-Servant stats, but at size 4 instead of 5, and make them tramplers...

**Comment by Ealb** [comment]
Also, while the random digressions can have lovely and entertaining results as did this one, I still need to try to avoid them if I'm ever to actually finish and release any of said results, sigh. Oh, the many joys of a short attention span...

**Comment by Ealb** [comment]
Oh god. Not to put bad ideas in my head, but it occurs to me that I still have the separated bits and pieces I used to make this, and the next <ahem> "logical" step is of course to make giant hoburgs...

**Comment by Ealb** [comment]
I... can't say I'm *proud* of myself, but I must admit there's some bizarrely amused satisfaction here:
giant_hoburg

**Comment by elmokki** [comment]
This is glorious, though the elephants are more beautiful.

I'm not sure they need trample. They look rather civilized and docile with those pot bellies and I bet they're easier to balance that way too. I mean, I suppose any bigger giant could trample physically, but few of them do.

**Pull request merged**
