### PR TITLE
Reduced/increased upkeep filters

### PR DESCRIPTION
**Pull request by Ealb**
Filters using the new #addupkeep command to directly manipulate effective costs for upkeep:
* Added T2/T3 power 1 filter that effectively reduces upkeep 40g/year (non-sacred)
* Added T2/T3 power -1 filter that effectively increases upkeep 40g/year (non-sacred)
* Added elite filter for gcost 15-30 elites that effectively reduces upkeep 8g/year and gives +1 mor
* Added elite filter for gcost 30+ elites that effectively reduces upkeep 16g/year and gives +1 mor
* Added sacred filter for gcost 15-30 elites that effectively reduces upkeep 6g/year and gives #neednoteat
* Added sacred filter for gcost 30+ elites that effectively reduces upkeep 12g/year and gives #neednoteat

### CODE REVIEW

**Comment by Ealb** [comment]
The mage filters might be too much - I went with +/- 50 for upkeep calculations (+/-3.3g per turn), but that seems like it might be a lot for power +/-1 - I know I have a bad track record with estimating what would be good in that regard.

**Comment by elmokki** [comment]
There's probably a semi-hidden command modifier like %gcost20% or something that is used for something and that may or may not work. That might be good here if it exists and works.

**Comment by elmokki** [comment]
This is what I was talking about (and I'm not 100% sure the thing you implemented works but I suppose you tested):

#new
#name "chaosrec10"
#type "chaosrec"
#basechance 0.05
#command "#chaosrec %cost10"
#chanceinc "command #chaosrec 50"
#chanceinc "command #chaospower 50"
#theme recruitment
#power 2
#end

**Comment by Ealb** [comment]
Ha, my search terms were too narrow when I looked for what you meant.
Actually, I haven't tested that mess yet, but it's how mage healing (and nothing else) is handled, and I walked through the relevant chunk of code when I turned it up. I'll probably look at this and my mess tonight; the scaling-by-cost rather than -by-tier looks like the better choice, though.

**Comment by Ealb** [comment]
Ugh, the %cost thing is a bit of a mess. It's redundantly processing the "#addupkeepcost %cost50" repeatedly - the command gets added to percentCostCommands an absurd number of times (#chaosrec does as well), which seems like it's usually at least 100 but I've seen as high as 1000. If the command uses %cost50 it still works because it'll overwrite that #addupkeepcost every time, but if it's the awkward-looking %cost-50, you end up with messes ranging from e.g. -3000 to -12000 because it subtracts the value from the running total. Moving the population of percentCostCommands to polish() fixes most of that, but there's still a few issues with how handleCommand deals with old arguments starting with %. When those are fixed, it's pretty much spot on, though getGoldCost() is returning too-high values for sacreds (at a glance, it looks like the *1.3 sacred cost mod might be getting applied to finalized prices rather than non-finalized prices).

**Comment by elmokki** [comment]
I am not entirely surprised there's something wrong there.

**Pull request merged**
