### PR TITLE
Ogre armor, ogreish FS

### PR DESCRIPTION
**Pull request by Ealb**
* Fairly complete set of armor for size-3 ogreish humanoids, to include such FS
* Enough limbs, etc. to do a moderately acceptable job of making ogreish size-3 FS

Not there yet, but soon:

mockup

### CODE REVIEW

**Comment by Ealb** [comment]
ogres

Still plodding along. Probably going to add bandar/muuch arms (already have heads and legs) and then start writing definitions for size-3s.

**Comment by elmokki** [comment]
They're gorgeous, however the lizard-thing on the first post is the most glorious thing. Honestly beings like that could be a race of their own almost.

**Comment by Ealb** [comment]
They are cute. I did heads for Fire, Frost, and Swamp drakes. Probably could do wyrverns too, come to think of it...

**Comment by Ealb** [comment]
Hmm. Looking at a mockup, there really *is* something to be said for quadruped draconians...

draconian

**Comment by elmokki** [comment]
That might actually suit quite well for some sort of Oriental Dragon (LA Jomon style) race.

**Comment by Ealb** [comment]
Four limbs good, six limbs better?

draconian2

**Comment by Ealb** [comment]
Hmm, I'd need to do a proper torso for them (size-3 FS all have thick fur-clad torsos like ogres), but I'll save my Gimp file where I was screwing around with these for possible future shenanigans.

**Pull request merged**
