### PR TITLE
Misc graphics

### PR DESCRIPTION
**Pull request by Ealb**
* Bandar thralls (all demographics) for illithid nations; I'm not entirely happy with these, but I've been picking at them on and off since December, so I just made myself finish them
* Ichtyid cavefish thralls
* Some more weird foul mounts/monsters I may or may not do something with

### CODE REVIEW

**Comment by elmokki** [comment]
I think these are great. However, the elephantoid is the greatest.

**Comment by Ealb** [comment]
The original plan was to scale it down and replace a bear or horse head with it, but then I noticed that a decapitated elephant was just the right size and almost exactly the right color to take the tentacles. And so...

Which of the boaring grubs looks better, BTW? I'm torn between the simple-but-cleaner head swap and the busier-but-less-cliche head-belly-tail look.

**Comment by elmokki** [comment]
I'd just put both in.

**Comment by Ealb** [comment]
...I will admit I'm also tempted to use the bandar thrall graphic as an uncivilized ape mount for pygmies...

**Pull request merged**
