### PR TITLE
[WIP] Refactor Nationgen with NationGenAssets

### PR DESCRIPTION
**Pull request by flash-fire**
Kind of WIP.  Problem is refactoring entity to have NationGenAssets would be a pain with the reflection going on, I think.

Going to add stuff to this but thought I'd push it to make sure no one duplicates works.

### CODE REVIEW

**Comment by flash-fire** [comment]
yeah don't merge this. Not sure if I ever want to merge this but it's an idea I guess.

**Comment by elmokki** [comment]
It makes sense to me to implement this, but do whatever you feel like is the best.

**Comment by flash-fire** [comment]
Sounds good.  In classic style, I merge conflict with myself hahaha.  I'll deal with the conflicts later & try to clean this up a bit.

**Comment by flash-fire** [comment]
Going to squash/merge this.  I think the code is robust enough.  Just some work will need to be done later to make this even better ideally.  But, I want to work on other things.

**Pull request merged**
