### PR TITLE
Gave several shapechange filters increased #maxage 

### PR DESCRIPTION
**Pull request by Ealb**
Devils, vine/metalmen, deepone to full age of second form; werefoo *2

### CODE REVIEW

**Comment by elmokki** [comment]
There is code that sets maxage to the same for both shapes based on primary shape. It will probably override your changes.

This was because on some Dom4 version the game crashed if the shapes had different maxages. Not sure if it was changed.

**Comment by elmokki** [comment]
The code should be in ShapeChangeUnit

**Comment by elmokki** [comment]
#maxage *2 will also only work when #maxage has been explicitly defined in NationGen, so it only works if the #maxage code thing happens before resolving those commands.

Regardless, do test.

**Comment by Ealb** [comment]
I went ahead and set these in the filter, not in the secondshape, so it overrides to the higher value.

I'll test the werefoos though - that does seem like a spot that's ripe for problems.

**Comment by elmokki** [comment]
If it's in the filter I suspect that it'll only work when the unit in question has #maxage specified when it's *2 and not static

**Comment by Ealb** [comment]
Aye, I'm suspicious that that's the case. It could be kludged by defining maxage for everything but that's an awful solution for a small amount of gain.

**Comment by elmokki** [comment]
The program already sets some default commands for races afaik. If it sets #maxage 50 which iirc is human default there that would solve it

**Comment by Ealb** [comment]
Aye, that's a clean, easy 1-line fix in Race.java

**Comment by Ealb** [comment]
Ha, and it's definitely needed because without it Dom4 interprets maxage as 0 so you end up with maximally oldage units upon recruitment.

**Pull request merged**
